language: cpp
compiler: g++
notifications:
  email: false
sudo: required
install:
- sudo apt-get -y update
- sudo apt-get -y install cmake
- chmod +x googleTester.sh
script: "bash -c ./googleTester.sh"
